language: python
python:
  - 3.7
  - 3.8
  - 3.9
  - 3.10-dev
before_install:
  - sudo apt-get install python-dev
install:
  - pip install pycodestyle
before_script:
  - pycodestyle --max-line-length=200 --ignore=E402 */*.py
script:
  - python setup.py test
